# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 497)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileBox = QtWidgets.QGroupBox(self.centralwidget)
        self.fileBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.fileBox.setObjectName("fileBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fileBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.openFile = QtWidgets.QPushButton(self.fileBox)
        self.openFile.setObjectName("openFile")
        self.horizontalLayout_2.addWidget(self.openFile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.processesTable = QtWidgets.QTableWidget(self.fileBox)
        self.processesTable.setObjectName("processesTable")
        self.processesTable.setColumnCount(3)
        self.processesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.processesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.processesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.processesTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.processesTable)
        self.horizontalLayout.addWidget(self.fileBox)
        self.resultBox = QtWidgets.QGroupBox(self.centralwidget)
        self.resultBox.setObjectName("resultBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.resultBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stepLabel = QtWidgets.QLabel(self.resultBox)
        self.stepLabel.setObjectName("stepLabel")
        self.horizontalLayout_4.addWidget(self.stepLabel)
        self.rrStep = QtWidgets.QSpinBox(self.resultBox)
        self.rrStep.setMinimum(1)
        self.rrStep.setMaximum(10)
        self.rrStep.setObjectName("rrStep")
        self.horizontalLayout_4.addWidget(self.rrStep)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.applyAlgorithms = QtWidgets.QPushButton(self.resultBox)
        self.applyAlgorithms.setObjectName("applyAlgorithms")
        self.horizontalLayout_3.addWidget(self.applyAlgorithms)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.resultsTable = QtWidgets.QTableWidget(self.resultBox)
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(4)
        self.resultsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.resultsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.resultsTable)
        self.horizontalLayout.addWidget(self.resultBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fileBox.setTitle(_translate("MainWindow", "Файл"))
        self.openFile.setText(_translate("MainWindow", "Открыть файл"))
        item = self.processesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "№"))
        item = self.processesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Начало"))
        item = self.processesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Время"))
        self.resultBox.setTitle(_translate("MainWindow", "Алгоритмы"))
        self.stepLabel.setText(_translate("MainWindow", "Шаг алгоритма  RR:"))
        self.applyAlgorithms.setText(_translate("MainWindow", "Применить алгоритмы"))
        item = self.resultsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Время"))
        item = self.resultsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FIFS"))
        item = self.resultsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "RR"))
        item = self.resultsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SJF"))

